### PR TITLE
Add workflows

### LINKED ISSUE #15: Add PyPI release workflows
## Feature Description
The library should be automatically uploaded to PyPI on release.

Reference release script https://github.com/vanderschaarlab/autoprognosis/blob/main/.github/workflows/release.yml

### LINKED ISSUE #16: [CI] Github workflows
## Description
Before releasing, the library should be tested on the matrix {MacOS, Windows, Linux} x {ython {3.7, 3.8, 3.9, 3.10} for compatiblity.

On each test scenario, all the unit tests should pass.

Reference workflow: https://github.com/vanderschaarlab/autoprognosis/blob/main/.github/workflows/test.yml

---

Additional notes:
* Add a notebook testing workflow a la https://github.com/vanderschaarlab/synthcity/blob/main/tests/nb_eval.py
* Include doctests in workflow
* As part of this, get rid of `requirements-dev.txt` and put that as testing mode in `setup.cfg`

### PR DESCRIPTION
**Pull request by DrShushen**
## Description
Closes #16, closes #15.
This PR adds two github workflows:
* [`test.yml`](https://github.com/vanderschaarlab/temporai/blob/DrShushen/GH-workflows/.github/workflows/test.yml) for running linting followed by tests, doctests, and notebook tests.
* [`release.yml`](https://github.com/vanderschaarlab/temporai/blob/DrShushen/GH-workflows/.github/workflows/release.yml) for building and then releasing to PyPI (triggered on GitHub release publishing).

Various configuration files have been updated as necessary.

## Affected Dependencies
Added [`dev` installation](https://github.com/vanderschaarlab/temporai/blob/DrShushen/GH-workflows/setup.cfg#L73) with all additional dependencies for dev and testing.

## How has this been tested?
- Added notebook testing: [`nb_eval.py`](https://github.com/vanderschaarlab/temporai/blob/DrShushen/GH-workflows/tests/nb_eval.py).
- See commands to run all tests in the [workflow](https://github.com/vanderschaarlab/temporai/blob/DrShushen/GH-workflows/.github/workflows/test.yml#L60).

## Checklist
- [X] I have followed the [Contribution Guidelines](https://github.com/vanderschaarlab/.github/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/vanderschaarlab/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] I have commented my code following the [van der Schaar Lab Styleguide](https://github.com/vanderschaarlab/.github/blob/main/STYLEGUIDE.md)
- [X] I have labelled this PR with the relevant [Type labels](https://github.com/vanderschaarlab/.github/labels?q=Type%3A)
- [X] My changes are covered by tests

### CODE REVIEW

**Comment by DrShushen** [comment]
**NOTE:** The PR is not ready for review yet, just created to trigger the workflows, in order to test them.

**Comment by DrShushen** [comment]
@bcebere - ready for review.
Have not tried the `release.yml` workflow yet.

**Review by bcebere — APPROVED** [review]
LGTM!

However, if you need to use PyTorch in the future, Python3.11 workflows will fail; PyTorch is not deployed there yet.

At the same time, Python 3.7 should still be supported for a while.

**Comment by DrShushen** [comment]
Okay, I may have to remove 3.11 when I add PyTorch.
I believe there might be some stuff in the code that doesn't support 3.7 but I will double check.

**Comment by DrShushen** [comment]
Testing `release.yml` by creating a dev release on PyPI

**Comment by DrShushen** [comment]
Found a "similar name" problem with the `temporai` name on PyPI:
* https://stackoverflow.com/a/71490005
* https://pypi.org/project/temporal/

May need to rename the library, at least for the purposes of PyPI project name. To be dealt with later.

**Pull request merged**
