### PR TITLE
Minor update to comments and .md files

### PR DESCRIPTION
**Pull request by DrShushen**
**UPDATE: `requests v2.30.0` yanked, the pin no longer necessary. PR will be merged to include minor update in md files/comments**

## Description

~This is a hotfix to avoid a bug with truncated responses with `requests v2.30.0` & `urllib3 v2`, see:~
* https://github.com/urllib3/urllib3/issues/3009
* https://github.com/psf/requests/issues/6439

~For now, pin dependency `urllib3<2` as this resolves the problem:~

## Affected Dependencies
N/A

## How has this been tested?
N/A

## Checklist
- [X] I have followed the [Contribution Guidelines](https://github.com/vanderschaarlab/.github/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/vanderschaarlab/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] I have commented my code following the [van der Schaar Lab Styleguide](https://github.com/vanderschaarlab/.github/blob/main/STYLEGUIDE.md)
- [X] I have labelled this PR with the relevant [Type labels](https://github.com/vanderschaarlab/.github/labels?q=Type%3A)
- [X] My changes are covered by tests

### CODE REVIEW

**Comment by DrShushen** [comment]
With this change, the "Tests Full" workflow should pass. Will merge once that is confirmed.

**Comment by pquentin** [comment]
Thank you for the report, @DrShushen! requests 2.30.0 was just yanked, so you don't have to pin: https://pypi.org/project/requests/2.30.0/. I would expect 2.30.1 to come out when the bug is fixed.

**Comment by DrShushen** [comment]
Rerunning Tests: Full on `main` following the yank to confirm this PR is not needed, will be closed once confirmed
https://github.com/vanderschaarlab/temporai/actions/runs/4875169994

**Comment by DrShushen** [comment]
To be merged after
https://github.com/vanderschaarlab/temporai/actions/runs/4875214001
passes.

**Pull request merged**
